# Dynamic chromatin accessibility in spermatogonial cells for transcriptional programmings from early postnatal to adult stages {#developmental}


\newpage

## Graphical Abstract

\newpage

## Abstract

\newpage

## Introduction

\newpage

## Results

### Enrichment of spermatogonial cells from postnatal and adult mouse testis

### Chromatin is remodeled   in spermatogonial cells during development

### Differentially accessible chromatin regions associate with distinct gene expression dynamics

### Differentially accessible chromatin regions associate with distinct epigenetic  profiles

### Accessibility changes at open chromatin regions are markedcarry by binding sites for distinct families of transcription factors

### Chromatin accessibility at transposable elements undergoes significant remodeling in the transition from postnatal to adult spermatogonia

\newpage

## Discussion

\newpage

## Methods

### Mouse husbandry 

### Germ cells isolation

### Spermatogonial cells enrichment by FACS

### Immunocytochemistry 

### RNA extraction and RNA-seq library preparation for RNA-seq

### Omni-ATAC Llibrary preparation for Omni-ATAC and sequencing

### RNA sequencing (RNA-seq)

### Assay for Transposase-Accessible Chromatin using sequening (Omni-ATAC)

### Chromatin iImmunnoprecipitation sequencing (ChIP-seq)

### Bisulfite sequencing (BS)

### High-throughput sequencing data analysis

### Figures

\newpage

## Data and materials availability

## Authors Contribution

## Competing interest

\newpage

## Acknowledgments

## Funding

\newpage

## Supplementary Figures

### Figure 1

### Figure 2

### Figure 3

### Figure 4

### Figure 5

### Figure 6

\newpage

## References