# Early life stress affects the miRNA cargo of epididymal extracellular vesicles in mouse {#ev}

Anar Alshanbayeva\textsuperscript{1,2,3}, **Deepak K Tanwar**\textsuperscript{1,2,3}, Martin Roszkowski\textsuperscript{1,2,3}, Francesca Manuella\textsuperscript{1,2,3}, Isabelle M Mansuy\textsuperscript{1,2,3,\#}
\newline
\newline
\textsuperscript{1}Laboratory of Neuroepigenetics, Brain Research Institute at the Medical Faculty of the University of Zurich.
\newline
\textsuperscript{2}Institute for Neuroscience of the Department of Health Sciences and Technology, ETH Zurich, Zurich, Switzerland.
\newline
\textsuperscript{3}Zurich Neuroscience Center, ETH and University of Zurich, Zurich, Switzerland.
\newline
\newline
\textsuperscript{\#}Corresponding author
\newline
\newline
**Journal:** _Biology of Reproduction_
\newline
DOI: [10.1093/biolre/ioab156](https://doi.org/10.1093/biolre/ioab156)
\newline
\newline
**Contributions:** _I performed data analysis with Anar Alshanbayeva, generated figures  with Anar Alshanbayeva, helped Anar Alshanbayeva in writing the manuscript, and revised manuscript with Anar Alshanbayeva._

\newpage

## Abstract

Sperm RNA can be modified by environmental factors and has been implicated in communicating signals about changes in a father’s environment to the offspring. The small RNA composition of sperm could be changed during its final stage of maturation in the epididymis by extracellular vesicles (EVs) released by epididymal cells. We studied the effect of exposure to stress in early postnatal life on the transcriptome of epididymal EVs using a mouse model of transgenerational transmission. We found that the small RNA signature of epididymal EVs, particularly miRNAs, is altered in adult males exposed to postnatal stress. In some cases, these miRNA changes correlate with differences in the expression of their target genes in sperm and zygotes generated from that sperm. These results suggest that stressful experiences in early life can have persistent biological effects on the male reproductive tract that may in part be responsible for the transmission of the effects of exposure to the offspring.

## Summary sentence

miRNA cargo of extracellular vesicles in cauda epididymis is altered by paternal exposure to early life stress. This correlates with changes in the expression of target genes in sperm and in zygotes generated from that sperm.

\newpage

## Graphical Abstract

## Key words 
epigenetics, epididymis, epididymosomes, early life stress, extracellular vesicles, miRNAs, sperm.

\newpage

## Introduction

\newpage

## Results

### Isolation of cauda epididymosomes confirmed by several methods

### The number and size of epididymosomes in adult males are not altered by postnatal stress

### miRNAs are persistently altered by postnatal stress in cauda epididymosomes

### mRNA targets of miRNAs from cauda epididymosomes are altered by postnatal stress in sperm and in zygotes

\newpage

## Discussion

\newpage

## Materials and methods

### Animals

### MSUS

### Tissue collection

### Electron microscopy images

### Epididymosomes isolation by ultracentrifugation

### Immunoblotting

### Nanoparticle tracking analysis

### RNA isolation and epididymosomes profiling

### Preparation and sequencing of sRNA-seq libraries from epididymosomes

### RT-qPCR

### Cholesterol measurements

### Bioinformatics data analysis

## Data availability

The datasets collected for this study are available as follows:
- sRNA-seq dataset of cauda epididymosomes before and after sizeselection: NCBI GEO under accession number [GSE175976](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE175976).
- Codes for bioinformatics analysis of RNA-sequencing datasets and
all corresponding differential expression analyses: Github repository https://github.com/mansuylab/alshanbayeva_et_al_2021[https://github.com/mansuylab/alshanbayeva_et_al_2021].
- Sperm and zygote sequencing datasets from previous publications
can be found in ArrayExpress database at EMBL-EBI ([www.ebi.ac.uk/arrayexpress](www.ebi.ac.uk/arrayexpress)) with the accession number [E-MTAB-5834](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-5834/) (sperm) and [E-MTAB-6589](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-6589/) (zygotes).

\newpage

## Authors' contributions

AA and IMM conceived and designed the study. FM and MR performed the MSUS breeding and collected tissue samples. AA and DKT performed data analysis and generated figures. AA wrote the manuscript with input from DKT and IMM. AA performed all
experiments for RNA sequencing and all molecular analyses. IMM supervised the project and raised funds.

## Grant Support
The work was supported by Swiss National Science Foundation (31003A-135715), ETH grants (ETH-10 15-2 and ETH-17 13-2), the Slack-Gyr Foundation, the Escher Foundation. The Mansuy lab is funded by the University Zürich, the Swiss Federal Institute of Technology, the Swiss National Science Foundation (31003A-135715), ETH grants (ETH-10 15-2 and ETH-17 13-2), the Slack-Gyr foundation, the Escher Foundation. Deepak K. Tanwar is supported by the Swiss Government Excellence Scholarship. Martin Roszkowski was funded by the ETH Zurich Fellowship (ETH-10 15-2).

## Acknowledgements

We thank Pierre-Luc Germain for advice on data analysis and for generating cumulative distribution plots, Irina Lazar-Contes for help with MSUS breeding, Silvia Schelbert for work on the animal license, Emilio Yandez at Function Genomics Center Zurich (FGCZ) for advice on the sRNA sequencing, Alekhya Mazumkhar for help with nanoparticle-tracking analysis, Yvonne Zipfel for animal care, Zurich Integrative Rodent Physiology facility for performing cholesterol measurements. We also thank Eloise Kremer, Ali Jawaid, and Mea Holmes for their initial contributions to the project.

**Conflict of interest:** The authors declare no conflict of interest.

\newpage

## Supplementary Figures

### Figure 1

\newpage

### Figure 2

\newpage

### Figure 3

\newpage

### Figure 4

\newpage

### Figure 5

\newpage

### Figure 6

\newpage

## Supplementary Tables

### Table 1

\newpage

### Table 2

\newpage

### Table 3

\newpage

### Table 4

\newpage

## References