graph TD

fastq(FASTQ)-->|FastQC|qc[Quality check]

qc-->|TrimGalore|QC[Quality control]

QC-->aln[Pseudo-alignment/ Alignment]

QC-->|multiQC|mqc[QC report]

style fastq stroke:black,stroke-width:2px,fill:#fff2e6;
style qc stroke:black,stroke-width:2px,fill:#fff2e6;
style QC stroke:black,stroke-width:2px,fill:#fff2e6;
style aln stroke:black,stroke-width:2px,fill:#fff2e6;
style mqc stroke:black,stroke-width:2px,fill:#fff2e6;