graph TD

title[<p><big><u>Data analysis piepeline</u></big></p>]
title-->fastq
style title fill:#FFF,stroke:#FFF
linkStyle 0 stroke:#FFF,stroke-width:0

fastq(FastQ)-->|FastQC|qc[Quality check]

qc-->|Trim Galore|QC{Trimming}

QC-->|Salmon|rnaAln[Pseudo-alignment]
QC-->|Rsubread|rnaAlnS[Alignment]
QC-->|Rsubread|shortAln[Alignment]
QC-->|Bismark|rrbsAln[Alignment]
QC-->|Bowtie2|atacAln[Alignment]

style fastq stroke:black
style qc stroke:black
style QC stroke:black

subgraph RNA-seq
rnaAln-->|limma|rnaDiff[Differential analysis]
rnaAlnS-->|DEXSeq|rnaExon[Differential exon usage]
rnaDiff-->|multiGSEA|rnaPath[Pathway analysis<br>KEGG, Reactome, GO]
rnaDiff-->|VIPER|rnaTF[TFBA]
rnaExon -->|PathwaySplice|pathSplice[Functional Analysis]
rnaAln-->|IsoformSwitchAnalyzeR|rnaExonS[Differential Splicing &<br>Isoform switching]
end

style rnaAln fill:MistyRose,stroke:black
style rnaAlnS fill:MistyRose,stroke:black
style rnaDiff fill:MistyRose,stroke:black
style rnaExon fill:MistyRose,stroke:black
style rnaPath fill:MistyRose,stroke:black
style rnaTF fill:MistyRose,stroke:black
style rnaExonS fill:MistyRose,stroke:black
style pathSplice fill:MistyRose,stroke:black


subgraph short RNA-seq
shortAln-->|shortRNA|sRNA[Statistical analysis]
end

style sRNA fill:PaleTurquoise,stroke:black
style shortAln fill:PaleTurquoise,stroke:black

subgraph WGBS/ RRBS
rrbsAln-->|Bismark|methEx[Methylation<br>extraction]
methEx-->|edgeR|dml[DML]
dml-->|rGREAT|great[Functional analysis]
methEx-->|dmrseq|dmr[DMR]
dmr-->|rGREAT|great[Functional analysis]
end

style rrbsAln fill:HoneyDew,stroke:black
style methEx fill:HoneyDew,stroke:black
style dml fill:HoneyDew,stroke:black
style dmr fill:HoneyDew,stroke:black
style great fill:HoneyDew,stroke:black

subgraph ATAC-seq/ ChIP-seq
atacAln-->|MACS2|PC[Peak calling]
PC-->|csaw/edgeR|daPC[Differential analysis]
daPC-->|HOMER|atacTF[TFBA]
daPC-->|rGREAT|atacTF[Functional analysis]
end

style atacAln fill:PeachPuff,stroke:black
style PC fill:PeachPuff,stroke:black
style daPC fill:PeachPuff,stroke:black
style atacTF fill:PeachPuff,stroke:black