  graph LR

  b(miRNAcluster_<br>2:10465287-10518279+)-->c(MI0005546_<br>mir-466d)

  subgraph 
  c-->d(MI0005546)
  c-->e(miR-466)
  e-->f(miR-466d)
  f-->g(miR-466d-5p)
  f-->h(miR-466d-3p)
  end

  b-->c1(MI0005506_<br>mir-466e)

  subgraph 
  c1-->d1(MI0005506)
  c1-->e1(miR-466)
  e1-->f1(miR-466e)
  f1-->g1(miR-466e-5p)
  f1-->h1(miR-466e-3p)
  end

  style b fill:#f7a8c8,stroke:#333,stroke-width:2px;
  style c fill:#cad1eb,stroke:#333,stroke-width:2px;
  style c1 fill:#cad1eb,stroke:#333,stroke-width:2px;
  style d fill:#cad1eb,stroke:#333,stroke-width:2px;
  style d1 fill:#cad1eb,stroke:#333,stroke-width:2px;
  style e fill:#cad1eb,stroke:#333,stroke-width:2px;
  style e1 fill:#cad1eb,stroke:#333,stroke-width:2px;
  style f fill:#cad1eb,stroke:#333,stroke-width:2px;
  style f1 fill:#cad1eb,stroke:#333,stroke-width:2px;
  style g fill:#cad1eb,stroke:#333,stroke-width:2px;
  style g1 fill:#cad1eb,stroke:#333,stroke-width:2px;
  style h fill:#cad1eb,stroke:#333,stroke-width:2px;
  style h1 fill:#cad1eb,stroke:#333,stroke-width:2px;
