# Dynamic chromatin accessibility in spermatogonial cells for transcriptional programmings from early postnatal to adult stages {#chapter1}

Irina Lazar-Contes\textsuperscript{1,2,3,$\dagger$}, **Deepak K Tanwar** \textsuperscript{1,2,3,$\dagger$}, Pierre-Luc
Germain\textsuperscript{1,2,3,4}, Isabelle M
Mansuy\textsuperscript{1,2,3,\#}\newline \newline
\textsuperscript{1}Laboratory of Neuroepigenetics, Brain Research
Institute at the Medical Faculty of the University of Zurich. \newline
\textsuperscript{2}Institute for Neuroscience of the Department of
Health Sciences and Technology, ETH Zurich, Zurich, Switzerland.\newline
\textsuperscript{3}Zurich Neuroscience Center, ETH and University of
Zurich, Zurich, Switzerland. \newline \textsuperscript{4}Statistical
Bioinformatics Group, Swiss Institute of Bioinformatics, Zurich,
Switzerland. \newline \newline \textsuperscript{$\dagger$}Equal
contributions \newline\newline \textsuperscript{\#}Corresponding
author \newline\newline 
__Contributions:__ *I performed data analysis, generated figures, wrote computational methods and figure captions, revised manuscript.*
