graph LR

  
  b(mt_tRNA-Ala)-->c(mt_tRNA-Ala-TGC)
  c-->d(mt_tRNA-Ala-TGC-1)
  d-->e(mt_tRNA-Ala-TGC-1-1)

  c-->g(mt_tRNA-Ala-TGC-2)
  g-->h(mt_tRNA-Ala-TGC-2-1)

  style b fill:#f7a8c8,stroke:#333,stroke-width:2px;
  style c fill:#cad1eb,stroke:#333,stroke-width:2px;
  style d fill:#cad1eb,stroke:#333,stroke-width:2px;
  style e fill:#cad1eb,stroke:#333,stroke-width:2px;
  style g fill:#cad1eb,stroke:#333,stroke-width:2px;
  style h fill:#cad1eb,stroke:#333,stroke-width:2px;