graph LR


s1((Seq1)) --> s11(TGAGGTAGTAGTTTGTACAGTT)
s2((Seq1)) --> s21(TGAGGTAGTAGTTTGTACAGT)

style s1 fill:white,stroke:red,stroke-width:2px;
style s2 fill:white,stroke:blue,stroke-width:2px;
style s11 fill:white,stroke:red,stroke-width:2px,stroke-dasharray: 5 5;
style s21 fill:white,stroke:blue,stroke-width:2px,stroke-dasharray: 5 5;