  graph LR

  b(tRNA-Ala)-->c(tRNA-Ala-AGC)
  c-->d(tRNA-Ala-AGC-4)
  d-->e(tRNA-Ala-AGC-4-1)

  b-->f(tRNA-Ala-CGC)
  f-->g(tRNA-Ala-CGC-1)
  g-->h(tRNA-Ala-CGC-1-1)

  style b fill:#f7a8c8,stroke:#333,stroke-width:2px;
  style c fill:#cad1eb,stroke:#333,stroke-width:2px;
  style d fill:#cad1eb,stroke:#333,stroke-width:2px;
  style f fill:#cad1eb,stroke:#333,stroke-width:2px;
  style e fill:#cad1eb,stroke:#333,stroke-width:2px;
  style g fill:#cad1eb,stroke:#333,stroke-width:2px;
  style h fill:#cad1eb,stroke:#333,stroke-width:2px;